from typing import List

class CardConnection:
    def __init__(self, reader: "str"): ...
    def connect(self) -> None: ...
    def disconnect(self) -> None: ...
    def release(self) -> None: ...
    def getATR(self) -> List[int]: ...
    def transmit(self, data: List[int]) -> tuple[bytes, int, int]: ...
