from typing import List

from smartcard.CardConnection import CardConnection
from smartcard.Reader import Reader

class ExclusiveConnectCardConnection:
    def __init__(self, connection: CardConnection) -> None: ...
    def connect(self) -> None: ...
    def disconnect(self) -> None: ...
    def release(self) -> None: ...
    def getATR(self) -> List[int]: ...
    def transmit(self, data: List[int]) -> tuple[bytes, int, int]: ...
    def lock(self) -> None: ...
    def unlock(self) -> None: ...
    def getReader(self) -> Reader: ...
