name: Full compatibility tests
on:
  schedule:
    # run daily
    - cron: "0 0 * * *"
  workflow_dispatch:

env:
  PIP_UPLOADED_PRIOR_TO: P0D

jobs:
  test-pip:
    name: Run test suite with pip installation
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.11", "3.12", "3.13", "3.14"]
        exclude:
          # hidapi does not build on Windows and does not have wheels for Python 3.14
          - os: windows-latest
            python-version: "3.14"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      # hidapi needs to be built from source for Python 3.14
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install --yes libudev-dev libusb-1.0-0-dev
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.14'
      - name: Install SDK
        run: pip install .
      - name: Run test suite
        run: python -m unittest -v
