name: Full compatibility tests
on:
  schedule:
    # run daily
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  test-pip:
    name: Run test suite with pip installation
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install SDK
        run: pip install .
      - name: Run test suite
        run: python -m unittest -v
